--- hid-ite8291r3/Makefile	2022-08-29 10:21:32.587619672 +0100
+++ hid-ite8291r3-patched/Makefile	2022-08-29 10:35:14.703162476 +0100
@@ -4,24 +4,9 @@
 
 obj-m += $(MODNAME).o
 
-KDIR = /lib/modules/$(shell uname -r)/build
-MDIR = /usr/src/$(MODNAME)-$(MODVER)
 
 all:
-	make -C $(KDIR) M=$(PWD) modules
+    make -C $(KDIR) M=$(PWD) modules
 
 clean:
-	make -C $(KDIR) M=$(PWD) clean
-
-dkmsinstall:
-	mkdir -p $(MDIR)
-	cp Makefile dkms.conf $(wildcard *.c) $(MDIR)/.
-	dkms add $(MODNAME)/$(MODVER)
-	dkms build $(MODNAME)/$(MODVER)
-	dkms install $(MODNAME)/$(MODVER)
-
-dkmsuninstall:
-	-rmmod $(MODNAME)
-	-dkms uninstall $(MODNAME)/$(MODVER)
-	-dkms remove $(MODNAME)/$(MODVER) --all
-	rm -rf $(MDIR)
+    make -C $(KDIR) M=$(PWD) clean
